# Lumo UI Plugin
# This file is used to store configurations for the Lumo UI Plugin
# Do not delete this file

ThemeName=AppTheme
ComponentsDir=modules/app/src/commonMain/kotlin/dev/koenv/libraryapi/app/ui
PackageName=dev.koenv.libraryapi.app.ui
# Uncomment this line if you are using Kotlin Multiplatform
KotlinMultiplatform=true