ktor:
  application:
    modules:
      - dev.koenv.libraryapi.ApplicationKt.module
  deployment:
    port: 8080
  development: $KTOR_DEVELOPMENT:true
  environment: $KTOR_ENV:development

jwt:
  domain: "https://127.0.0.1:8080/"
  audience: "library-api"
  realm: "Access to Library API"
  secret: "$JWT_SECRET:7ea529c97a5c3a28acced8bcbc5f2d8d"

db:
  type: "$DB_TYPE:h2"             # mysql | h2
  host: "$DB_HOST:localhost"
  port: "$DB_PORT:3306"
  name: "$DB_NAME:libraryapi"
  user: "$DB_USER:root"
  password: "$DB_PASSWORD:password"
  file: "$DB_FILE:./build/db/libraryapi"  # for h2 file-based mode
