CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, "role" VARCHAR(20) NOT NULL, created_at DATETIME(9) DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE users ADD CONSTRAINT users_email_unique UNIQUE (email);
